### ISSUE TITLE
LineItem: Property types

### ISSUE THREAD

**Issue by tmmgrafikr** [grafikr/shopify-typescript#12]
https://github.com/grafikr/shopify-typescript/blob/8db519772e28502c4bab725b8d8180c653772a76/type/LineItem.ts#L3

These could also consist of `array | object`

**Comment by andershagbard** [comment]
Is that the same as `any` ?

**Comment by tmmgrafikr** [comment]
`any` would also cover stuff like functions, not sure if a cleaner way to write it.

**Comment by tmmgrafikr** [comment]
I think so 🤷
